const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.destroy,
		C3.Behaviors.Physics,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.CompareSpeed,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.OnLayoutStart
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{ScrollTo: 0},
	{BoundToLayout: 0},
	{Player: 0},
	{Solid: 0},
	{Sine: 0},
	{IronBar: 0},
	{Keyboard: 0},
	{Danger: 0},
	{Ground: 0},
	{EvilBG: 0},
	{BlueBG: 0},
	{Sprite: 0},
	{Text: 0},
	{Ground2: 0},
	{Death: 0},
	{NextLevel: 0},
	{Crossbar: 0},
	{Crystal: 0},
	{DestroyOutsideLayout: 0},
	{Physics: 0},
	{Sprite2: 0},
	{Audio: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	IronBar: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	Danger: class extends self.ITiledBackgroundInstance {},
	Ground: class extends self.ITiledBackgroundInstance {},
	EvilBG: class extends self.ITiledBackgroundInstance {},
	BlueBG: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Ground2: class extends self.ITiledBackgroundInstance {},
	Death: class extends self.ITiledBackgroundInstance {},
	NextLevel: class extends self.ITiledBackgroundInstance {},
	Crossbar: class extends self.ITiledBackgroundInstance {},
	Crystal: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {}
}